// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArei86-0VO4Md3maRPd8hcrkQlfb3KZdk',
    appId: '1:670540111346:web:644e0841f41e3506615f6b',
    messagingSenderId: '670540111346',
    projectId: 'fir-1-cf35a',
    authDomain: 'fir-1-cf35a.firebaseapp.com',
    storageBucket: 'fir-1-cf35a.firebasestorage.app',
    measurementId: 'G-T2ZZFERJGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOhBCvXgwVRb9syfqkRXSWPINWOuS5X-Y',
    appId: '1:670540111346:android:f53aab955a78f613615f6b',
    messagingSenderId: '670540111346',
    projectId: 'fir-1-cf35a',
    storageBucket: 'fir-1-cf35a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRm6IW8-xWU-Vp7VMLmfKW4ZjGSAUs9iQ',
    appId: '1:670540111346:ios:ad4e19a5b5a20dab615f6b',
    messagingSenderId: '670540111346',
    projectId: 'fir-1-cf35a',
    storageBucket: 'fir-1-cf35a.firebasestorage.app',
    iosBundleId: 'com.indiatechtimes.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRm6IW8-xWU-Vp7VMLmfKW4ZjGSAUs9iQ',
    appId: '1:670540111346:ios:ad4e19a5b5a20dab615f6b',
    messagingSenderId: '670540111346',
    projectId: 'fir-1-cf35a',
    storageBucket: 'fir-1-cf35a.firebasestorage.app',
    iosBundleId: 'com.indiatechtimes.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArei86-0VO4Md3maRPd8hcrkQlfb3KZdk',
    appId: '1:670540111346:web:5832b94f8260a5d1615f6b',
    messagingSenderId: '670540111346',
    projectId: 'fir-1-cf35a',
    authDomain: 'fir-1-cf35a.firebaseapp.com',
    storageBucket: 'fir-1-cf35a.firebasestorage.app',
    measurementId: 'G-C8K1EMZDRZ',
  );
}
